# Setup
title: Peter Hrynkow - Vancouver Tech Leader
email: peter@labwire.ca
description: > # this means to ignore newlines until "baseurl:"
  Peter Hrynkow is an engineering leader focused on AI enablement, automation, and developer productivity.
# tagline: Peter writes code and words about code.
# baseurl: "/peterhrynkow.com"
url: "https://peterhrynkow.com"
twitter_username: peterhry
github_username:  peterhry

# About/contact
author:
  name: Peter Hrynkow
  url: https://peterhrynkow.com
  github: https://github.com/peterhry
  stackoverflow: https://stackoverflow.com/users/1345271/peterhry
  linkedin: https://linkedin.com/in/peterhry
  codepen: https://codepen.io/peterhry
  twitter: https://twitter.com/peterhry
#Others
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed